# Generated by Django 5.1.2 on 2025-02-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
