# Generated by Django 5.1.2 on 2025-02-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_feedback_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
